### ISSUE TITLE
Projet trop long et trop lourd à cloner

### ISSUE THREAD

**Issue by kilbith** [Unarelith/OpenMiner#107]
On dispose pas tous de connexions super rapides... Trop de dépendances non-essentielles comme `sol2`. Le binding Lua aurait pu être fait sans utiliser une lib.

En plus la doc ne mentionne même pas que le projet contient des submodules.

**Comment by Unarelith** [comment]
Merci de créer des tickets en anglais uniquement.
Mais puisque tu l'as créé en français je vais répondre en français.

`sol2` est une dépendance essentielle, puisque c'est à travers cette dernière qu'OpenMiner utilise Lua. Cette bibliothèque est là pour simplifier les interactions entre les deux langages.
Tu peux essayer de recoder la partie interaction Lua/C++ si tu veux hein, mais ça ne sera jamais aussi pratique et performant que `sol`.

Le projet est effectivement lourd à cause de ses dépendences, mais c'est un téléchargement unique, qui se fait une seule fois. Je ne vois pas en quoi c'est un problème.

Et par rapport aux submodules, le but est de faciliter la gestion des dépendences, et tout est géré par CMake, tu n'as même pas besoin de faire un `git clone --recursive`, donc la mention dans la doc n'est pas tellement nécessaire en fait.

Donc je ferme ce ticket.

**Comment by kilbith** [comment]
Je vois pas en quoi le fait d'ajouter un wrapper améliore les performances par rapport à utiliser directement l'API C de Lua...

**Comment by Unarelith** [comment]
Je n'ai jamais dit que le fait d'ajouter un wrapper améliorait les performances, c'est le contraire. La surcouche qu'il est nécessaire de créer au dessus de l'API C de Lua causera forcément une perte de perfs. Autant prendre le [wrapper le plus performant](https://sol2.readthedocs.io/en/latest/benchmarks.html) donc.

**Comment by kilbith** [comment]
> Je n'ai jamais dit que le fait d'ajouter un wrapper améliorait les performances

Ah ?
> Tu peux essayer de recoder la partie interaction Lua/C++ si tu veux hein, mais ça ne sera jamais aussi pratique et performant que sol.

**Comment by Unarelith** [comment]
... Tu es sûr d'avoir lu ? J'ai dit que ton implémentation potentielle de l'interaction Lua/C++ dans OpenMiner serait pas aussi performante que `sol`. Je n'ai jamais dit que le wrapper améliore les perfs.

**Comment by Unarelith** [comment]
Et puis si on doit réinventer la roue pour tout ce qu'on code, autant coder notre propre ECS et drop `entt`, autant coder notre propre wrapper Lua et drop `sol`, mais c'est beaucoup de taff et je vois pas l'intérêt de perdre du temps là dessus.

**Comment by kilbith** [comment]
Donc pourquoi ne avoir opté pour un moteur 3D pour poursuivre dans cette direction ?

Je pense pas que ton projet ira aussi loin que Minetest. Bonne chance.

**Comment by Unarelith** [comment]
Parce que ce n'est pas nécessaire. Par exemple Minetest utilise Irrlicht, mais sur pas mal de points c'est plutôt quelque chose dont ils essaient de se débarasser qu'un avantage.
Pour créer un moteur de jeu avec des graphismes aussi simple, utiliser un moteur 3D est complètement overkill.

> Je pense pas que ton projet ira aussi loin que Minetest. Bonne chance.

Par contre ce genre de choses je n'apprécie pas. Je fais ce projet pour le fun et tant mieux si ça débouche sur quelque chose de viable à l'avenir. Ton avis ne m'intéresse pas, et ce n'est pas l'endroit pour l'émettre.

J'ai souvenir que tu étais banni du GH de Minetest. Je ne sais pas pourquoi tu l'étais, ni pourquoi tu ne l'es plus actuellement, mais ne viens pas trainer dans mes pattes, je n'ai pas besoin de toi.

**Comment by kilbith** [comment]
Tg fdp
