### ISSUE TITLE
Sun rendering incorrectly on windows

### ISSUE THREAD

**Issue by mDiyo** [Unarelith/OpenMiner#159]
Version: OpenMiner 0.0.10-pre1
Platform: Windows x64, Windows 10 OS

The sun appears to render incorrectly in bizarre ways on a windows machine. The sun has a halo effect that appears in the right spot, but with some oddities. The sun image is offset in a different place and displays the moon texture instead of the sun.
![skybox](https://user-images.githubusercontent.com/1430358/87843590-b2330c80-c86a-11ea-983a-961bed38590b.png)
![realsun2](https://user-images.githubusercontent.com/1430358/87843558-7b5cf680-c86a-11ea-85b8-8504512fd511.png)
![newsun](https://user-images.githubusercontent.com/1430358/87843565-844dc800-c86a-11ea-960a-9d73aa0a7dc7.png)

**Comment by Unarelith** [comment]
For the sun it looks like only 1/4 of the full texture displayed. :thinking:

**Comment by Unarelith** [comment]
May be fixed by [Gitea#26](https://git.unarelith.net/Unarelith/OpenMiner/pulls/26)

**Comment by Unarelith** [comment]
Fixed by 9c5f1b9
