### ISSUE TITLE
Using pause menu when mining will keep the latter enabled until left-click is pressed again

### ISSUE THREAD

**Issue by Trnrr** [Unarelith/OpenMiner#163]
Built from commit: b763b1aa8f84e96fda93fec6c5814cf4a8ca8a17
OS: Windows 10

Steps to reproduce:
1) ./openminer -s
2) Hold left click - to start mining
3) Press ESC - to open pause menu
4) Release left click - as if you were to stop mining
5) Press ESC - to close the menu
6) Mining is now enabled until you press left click again

**Comment by Unarelith** [comment]
Should be fixed in https://github.com/Unarelith/OpenMiner/commit/c52b831552e21198095680cbde112db2a587da2f, can you please check?

**Comment by Trnrr** [comment]
ESC key is fixed. I just tried it using the inventory and creative inventory keys and that also has the same issue still . I didn't think to test that originally as well.

**Comment by Unarelith** [comment]
Ahhh, ok I'll fix them too then

**Comment by Unarelith** [comment]
Should be fixed with https://github.com/Unarelith/OpenMiner/commit/c518334e5be35562c0d483a7b1468ab6a03aff97, please confirm
