### ISSUE TITLE
Destroying the top or bottom half of the door will crash the game

### ISSUE THREAD

**Issue by Trnrr** [Unarelith/OpenMiner#164]
Built from commit: b763b1aa8f84e96fda93fec6c5814cf4a8ca8a17
OS: Windows 10

Steps to reproduce:
1) ./openminer -s
2) Place down wood door
3) Destroy top or bottom half of it
4) Game crashes and closes instantly

It closes right away and I am unable to see what the console says or find where the log files are stored (if there are any). Also when I was testing one time when I was destroying the bottom half of the door it regenerated and nothing happened. This was right after I opened the world so it might have just been caused by that lag. I waited a second and did it again and it crashed.

**Comment by Unarelith** [comment]
@Trnrr probably fixed by https://github.com/Unarelith/OpenMiner/commit/0564e1cb70b7834933de3150ec2780c2e8f944b5, can you please check?

**Comment by Trnrr** [comment]
Fixed!
