### ISSUE TITLE
Using a hoe on grass/dirt causes the game to crash

### ISSUE THREAD

**Issue by Trnrr** [Unarelith/OpenMiner#165]
Built from commit: b763b1aa8f84e96fda93fec6c5814cf4a8ca8a17
OS: Windows 10

Steps to reproduce:
1) ./openminer -s
2) Grab your diamond hoe (only time you should ever have one)
3) Right click grass or dirt
4) Game crashes with the error
When right clicking grass: `[17:47:54] [E] [server] Fatal error at Registry.cpp:142: Unknown block: default:farmland                                                                          Fatal error at Registry.cpp:150: Unknown item: default:grass`
When right clicking dirt: `[17:49:03] [E] [server] Fatal error at Registry.cpp:142: Unknown block: default: farmland    Segmentation fault`

**Comment by Unarelith** [comment]
I fixed this issue in https://github.com/Unarelith/OpenMiner/commit/112886111b0fcaf1234885ef7152cdc0da045331, could you check if it also worked for you please?

**Comment by Trnrr** [comment]
Fixed!
