### ISSUE TITLE
F11 doesn't maximize to fullscreen when resolution is set to 1280x720 in the client.lua file

### ISSUE THREAD

**Issue by Trnrr** [Unarelith/OpenMiner#166]
Built from commit: b763b1aa8f84e96fda93fec6c5814cf4a8ca8a17
OS: Windows 10
Monitor size: 1920x1080

When hitting F11 after the resolution is set to 1280x720 it doesn't go fullscreen. It keeps the same screen size and goes to the top left of the screen.

Steps to reproduce:
1) Open \OpenMiner\config\client.lua
2) Change values to screenWidth = 1280 & screenHeight = 720
3) Run ./openminer -s
3) Press F11 to go into fullscreen
4) Get the following window instead 
![image](https://user-images.githubusercontent.com/20446954/88238800-496fd980-cc48-11ea-936e-bc12788abc8b.png)
5) If you press F11 2 more times it will maximize to the correct size

**Comment by Unarelith** [comment]
Can't reproduce on Linux, will check on Windows when I have the time

**Comment by Unarelith** [comment]
@Trnrr can you confirm this is fixed please?

**Comment by Trnrr** [comment]
Fixed!
