### ISSUE TITLE
Partial texture packs cause a variety of issues

### ISSUE THREAD

**Issue by mDiyo** [Unarelith/OpenMiner#167]
Version: OpenMiner 0.0.10-pre4
Platform: Windows 10 x64

Reproduction steps: Create a texture pack, delete files so that some of them are "missing". Change texture packs afterwards.

A texture pack with only one file turns everything into that texture. This may be intended behavior or a bug. This particular pack only has dirt in it.
![baddirt_2](https://user-images.githubusercontent.com/1430358/88487307-c47f0b80-cf38-11ea-839b-6fdfa79a75f8.png)

Changing to another texture pack afterwards loads a bunch of items onto everything.
![notdirt_1](https://user-images.githubusercontent.com/1430358/88487353-2c355680-cf39-11ea-94c3-48f95b833acd.png)

Rebooting the game and starting from more textures: This pack has dirt, grass, and all of the overlays and files that go with it. The textures are warped, stretched, or missing in various ways.
![partial_pack_1](https://user-images.githubusercontent.com/1430358/88487367-4b33e880-cf39-11ea-9bca-6d563f02cf18.png)

Changing to another texture pack afterwards has things working... odd. Newly loaded chunks look fine and old ones have the same issue as before.
![partial_pack_2](https://user-images.githubusercontent.com/1430358/88487383-643c9980-cf39-11ea-93de-4313add385d4.png)

**Comment by Unarelith** [comment]
@mDiyo may have been fixed by https://github.com/Unarelith/OpenMiner/commit/4337868fde906d20625ed8a29af8f93d15e1e184
Do you need another test release to make sure this is fixed, or can you compile yourself?

**Comment by Unarelith** [comment]
I'll consider it as fixed for now then
