### ISSUE TITLE
VS 2019 compile error

### ISSUE THREAD

**Issue by Alad53** [Unarelith/OpenMiner#179]
![23](https://user-images.githubusercontent.com/86076716/122621293-c5171800-d09d-11eb-8c99-a79448101245.JPG)

My Settings:
![435](https://user-images.githubusercontent.com/86076716/122621333-deb85f80-d09d-11eb-88d1-5ea87c59d85f.JPG)
![57](https://user-images.githubusercontent.com/86076716/122621355-f2fc5c80-d09d-11eb-8ecf-36b0531b23d7.JPG)

**Comment by Unarelith** [comment]
Please try to update VS2019. And please compile latest `master` commit.

If you still have the problem after that, let me know.

**Comment by Alad53** [comment]
@Unarelith,

VS 2019  and OpenMiner I am using the latest version

My VS 2019 Version:

![s](https://user-images.githubusercontent.com/86076716/122647995-b9743180-d12f-11eb-8f26-93a25477f240.JPG)

Errors & Warnings: 

![24](https://user-images.githubusercontent.com/86076716/122648078-0b1cbc00-d130-11eb-9efc-7450db3e2f42.JPG)

👎 
![3224](https://user-images.githubusercontent.com/86076716/122648301-55eb0380-d131-11eb-91dd-54eb751fe24e.JPG)

**Comment by Unarelith** [comment]
Fixed in https://github.com/Unarelith/OpenMiner/commit/e2f288cc86931cc8383108373e62d51d0a62d3fb
