### ISSUE TITLE
Cannot open OpenMiner Caused by fatal error

### ISSUE THREAD

**Issue by quentin452** [Unarelith/OpenMiner#185]
I Clicked on openminer.exe

Logs : 
[08:41:43] [D] [client] Fatal error at XMLFile.cpp:87: Failed to load resources/config/textures.xml
Error 3 : File not found.

Using this tutorial:

https://github.com/Unarelith/OpenMiner/wiki/Compiling-on-Windows-with-Visual-Studio-2019
Step 1: Installation of required tools

Git

    Install Git using the [official installer](https://bit.ly/3IwLRFu)
        During Git installation, make sure to select "commit Unix-style line endings" when prompted

CMake

    Install CMake using the CMake Installer: [https://cmake.org/download/](https://bit.ly/3IwLRFu)
        During CMake installation make sure to add CMake to system PATH

Visual Studio 2019

    Install Visual Studio Community 2019: https://visualstudio.microsoft.com/en/downloads/
    During installation check "C++ for desktop applications" and click "Install"

Step 2: OpenMiner compilation

    Open a PowerShell or cmd.exe
    Clone the repository using git clone https://github.com/Unarelith/OpenMiner
    Go inside OpenMiner folder using cd OpenMiner
    Run these commands:
        cmake -B build -G "Visual Studio 16 2019" .
        cmake --build build (you can continue reading instead of running this command if you want to compile using Visual Studio GUI)

I used Step 3: Running OpenMiner : 
Using Visual Studio

    Open build/openminer.sln with Visual Studio
    Right click on openminer project, then Properties → Debugging → Working Directory → Set to ..\..\..
    Go to solution properties → Common Properties → Startup Project and select Multiple startup projects
    Select Start for openminer
    Reorder the list so that openminer is the first one
    Run the solution ( for my case Build solution)

**Comment by quentin452** [comment]
I needed to add it manually

**Comment by Unarelith** [comment]
It's actually surprising, it's supposed to find the file if you set the working directory correctly...

I'm unable to reproduce the issue on my end

**Comment by Cyclopropinon** [comment]
same issue here.
i followed the ubuntu instructions
```
./openminer
[23:15:33] [E] [client] Fatal error at XMLFile.cpp:85: Failed to load resources/config/textures.xml 
Error 3 : File not found. 
Speicherzugriffsfehler (Speicherabzug geschrieben)
```
the last line means it accessed memory outside of allocated ones (Killsignal 2, SIGINT)

**Comment by Cyclopropinon** [comment]
btw what should be the correct working directory?
I am in the build directory

**Comment by Unarelith** [comment]
As mentioned in the README, the working directory should be the repo root

**Comment by Cyclopropinon** [comment]
ah yea mb
now it works
it isnt really obvious tho
would be nice if you add a notice in step 3 of the [compiling page](https://github.com/Unarelith/OpenMiner/wiki/Compiling-on-Linux#step-3-running-openminer)

**Comment by Unarelith** [comment]
It's implicit in step 3 since I wrote the actual commands to run, and they take that in account
