### ISSUE TITLE
Texture additions and fixes

### ISSUE THREAD

**Issue by LordDeatHunter** [Unarelith/OpenMiner#63]
- [x] Make this temporary texture for missing files instead of crashing the game:
![missingTexture](https://user-images.githubusercontent.com/26803198/75185997-5c3cbb80-5747-11ea-9d5d-e827961d29f1.png)
- [ ] ~~Make multiple textures for a single block (Dirt with pebbles, dirt with grass, normal dirt, etc.).~~

**Comment by Unarelith** [comment]
Those should be two separated issues imo, one for the placeholder texture when the file is not found, one for the multiple texture for a single block.

The second one is long-term so it doesn't need an issue right now.

If we make a ticket for every idea we have, it'll be really hard to keep track of them.

**Comment by Unarelith** [comment]
First problem fixed by https://github.com/Unarelith/OpenMiner/commit/1d4fe0a11ebb177496414c7e821c2c079b438352

**Comment by Unarelith** [comment]
I'm closing this issue since the second one is way too long-term to be thinking about it now.
