### ISSUE TITLE
Day/night cycle

### ISSUE THREAD

**Issue by Unarelith** [Unarelith/OpenMiner#73]
- [x] Block lighting should change depending on the in-game time (shader-only effect)
- [x] Sky/fog color should change too
- [x] Sun and moon basic display (may require a skybox)
- [x] Stars (may require a skybox)

**Comment by RobertZenz** [comment]
> Sun and moon basic display

You could allow to register a celestial body, which is simply a quad with a texture, and the mod controls the location on the skybox with every tick of the game.

**Comment by Unarelith** [comment]
Yep something alike is planned as part of the Sky API, [more details here](https://github.com/Unarelith/OpenMiner/issues/76)
