### ISSUE TITLE
Find better assets

### ISSUE THREAD

**Issue by Unarelith** [Unarelith/OpenMiner#9]
I'm currently using official Minecraft assets, and I shouldn't do that.

**Comment by tomlister** [comment]
Have an option to use official assets (from a legitimate copy of minecraft) or use your own texture pack.

**Comment by Unarelith** [comment]
#28 will fix this problem once it's completely done

**Comment by tacotexmex** [comment]
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/1242533-pixel-perfection-now-with-polar-bears-1-11

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/1245112-snowsong-the-epic-sound-pack-sound-resource-pack
