### ISSUE TITLE
Use LuaJIT

### ISSUE THREAD

**Issue by atomicbitty** [Unarelith/OpenMiner#91]
Vanilla Lua is OK for certain tasks, but as I see you want to use Lua for terrain generation and entity behaviour, and this will definitely slow down things to unacceptable speeds. If you care about performance I would recommend you to use LuaJIT: it's reasonably fast (even faster than Java in some cases) and well optimized. I didn't find any C++ wrapper for convenience, but if you are interested you could take a look at luajit.org.

**Comment by Unarelith** [comment]
Don't worry, this is planned. :)

Moreover, `sol2` can be used with LuaJIT, so it's not a problem.
