### ISSUE TITLE
Windows version doesn't work with packet compression enabled

### ISSUE THREAD

**Issue by Unarelith** [Unarelith/OpenMiner#97]
As the title says.

The client says it receives a packet with an ID equal to something like 6418 which is impossible.
This only happens when packet compression is enabled.

I think the server receives a compressed packet, even though it's supposed to be uncompressed during reception.

**Comment by atomicbitty** [comment]
Is that why the game is crashing when I press play?

**Comment by Unarelith** [comment]
Probably, which version are you running, and how do you run it?
This is fixed in `sfml25` branch though.
